backend:
  name: github
  repo: VRARKvant/VRKvant
  branch: main
  base_url: https://vr-kvant.vercel.app
  auth_endpoint: api/auth

media_folder: "img/other"
public_folder: "img/other"

collections:
  - name: "articles"
    label: "Все статьи"
    folder: "articles"
    extension: "md"
    format: "yaml-frontmatter"
    create: true
    recursive: true
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Текст", name: "body", widget: "markdown" }
